---
- name: 安装命令补全工具
  yum: name=bash-completion state=present

- name: 配置环境变量
  shell: kubectl completion bash > /etc/bash_completion.d/kubectl
  ignore_errors: yes

- name: 配置.bashrc
  lineinfile:
    path: ~/.bashrc
    line: "source /etc/bash_completion.d/kubectl"

- name: 开启keepalived脚本检测
  shell: sed 's/^#*//g' /etc/keepalived/keepalived.conf -i

- name: 重启keepalived
  systemd: name=keepalived enabled=yes state=reloaded

- block:
  - import_tasks: dashboard.yaml
  - import_tasks: ingress-nginx.yaml
  - import_tasks: metrics.yaml
  when: cluster_role=='master'
