---
- name: 获取metrics配置
  copy: src=components.yaml dest={{ k8s_work_dir }}/
  
- name: 安装metrics
  shell: kubectl apply -f {{ k8s_work_dir }}/components.yaml
  ignore_errors: yes
  register: install_metrics_info
- debug: var=install_metrics_info.stdout_lines verbosity=0

- name: 查看pods状态
  shell: kubectl get pods -n kube-system
  ignore_errors: yes
  register: pod_info
- debug: var=pod_info.stdout_lines verbosity=0


