---
- name: 1.安装必要系统工具
  yum:
    name: ['yum-utils','device-mapper-persistent-data','lvm2']
    state: installed

- name: 2.添加软件源信息
  shell: yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo

- name: 3.更新并安装Docker-CE
  yum: name={{ docker_version }} state=installed

- name: 4.开机自启动docker
  systemd: name=docker state=restarted enabled=yes

- name: 5.配置镜像加速
  copy: src=daemon.json dest=/etc/docker/daemon.json

- name: 6.重启docker
  shell: systemctl daemon-reload
