---
- name: 0.系统初始化
  gather_facts: false
  hosts: k8s 
  roles:
    - common
  tags: common 

- name: 1.安装ipvs
  gather_facts: false
  hosts: k8s
  roles:
    - ipvs
  tags: ipvs

- name: 2.部署Docker
  gather_facts: false
  hosts: k8s 
  roles:
    - docker 
  tags: docker

- name: 3.部署K8S
  gather_facts: false
  hosts: k8s 
  roles:
    - kubernetes 
  tags: kubernetes

- name: 4.部署HA
  gather_facts: false
  hosts: lb
  roles:
    - ha
  tags: ha

- name: 5.kubeadm
  hosts: k8s
  roles:
    - kubeadm
  tags: kubeadm

- name: 6.addons
  gather_facts: false
  hosts: master
  roles: 
    - addons
  tags: addons
