---
- name: 1.获取内核版本
  shell: uname -r | cut -c 1-4
  register: kernel_version
  ignore_errors: true
- debug: msg={{kernel_version.stdout}}

- block:
  - name: 2.分发ipvs配置内核版本<4.19
    copy: src=ipvs.modules dest=/etc/sysconfig/modules/ipvs.modules mode=755
  when: kernel_version.stdout is version(4.19,"<")

- block:
  - name: 2.分发ipvs配置内核版本>=4.19
    copy: src=ipvs.modules.419 dest=/etc/sysconfig/modules/ipvs.modules mode=755
  when: kernel_version.stdout is version(4.19,">=")

- name: 3.安装ipvs管理工具
  yum: 
    state: present
    name: ['ipvsadm','ipset','sysstat','conntrack','libseccomp']

- name: 4.配置ipvs重启自动加载
  shell: bash /etc/sysconfig/modules/ipvs.modules
