---
- hosts: all:!localhost
  name: Reboot all nodes
  become: yes
  tasks:
    - name: reboot nodes
      shell: sleep 5 && shutdown -r now "Ansible reboot"
      async: 1
      poll: 0
      ignore_errors: true
      register: result
    - debug:
        var: result
